name: Cleanup Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This schedule runs the workflow at midnight every day
  push:

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  cleanup-stale-branches:
    runs-on: ubuntu-latest
    run:
      |
      print('Hello')
    # steps:
    #   - name: Cleanup Stale Branches
    #     uses: cbrgm/cleanup-stale-branches-action@v1
    #     with:
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #       repository: ${{ github.repository }}
    #       ignore-branches: "main"
    #       ignored-prefixes: "feature/,bugfix/"
    #       last-commit-age-days: 10
    #       dry-run: false
    #       rate-limit: true