on:
  push:

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  terraform-cmt:
    name: Terraform Comment
    runs-on: ubuntu-latest
    steps:
      - uses: shmokmt/actions-setup-tfcmt@v2